#!/bin/bash
STATUS=`getenforce`
echo "current SELinux status is $STATUS, continue to modify status changes..."
case "$STATUS" in
   "Disabled")
        echo "Choose your option by pressing number 1.Enforcing 2.Permissive"
        read select
        case $select in
                1) echo "processing Enforcing..."
                   sed -i '7s/enforcing/disabled/g' /etc/selinux/config
                ;;
                2) echo "processing Permissive..."
                   sed -i '7s/disabled/permissive/g' /etc/selinux/config
                ;;
        esac
        ;;
   "Enforcing")
        echo "choose your option by pressing number 1.Permissive 2.Disable"
        read select1
        case $select1 in
                1) echo "processing Permissive..."
                   sed -i '7s/enforcing/permissive/g' /etc/selinux/config
                ;;
                2) echo "processing Disable..."
                   sed -i '7s/enforcing/disabled/g' /etc/selinux/config
                ;;
        esac
        ;;
   "Permissive")
        echo "Choose your option by pressing 1.Enforcing 2.Disable"
        read select2
        case $select2 in
                1) echo "processing Enforcing..."
                   sed -i '7s/permissive/enforcing/g' /etc/selinux/config
                ;;
                2) echo "processing Disable..."
                   sed -i '7s/permissive/disabled/g' /etc/selinux/config
                ;;
        esac
        ;;
esac
exit
